# Generated by Django 5.2.15 on 2026-06-28 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_etaria', models.CharField(choices=[('crianca', 'Criança (7–12)'), ('adolescente', 'Adolescente (13–17)'), ('adulto', 'Adulto (18+)')], default='adulto', max_length=20)),
                ('nivel_atual', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('xp_total', models.IntegerField(default=0)),
                ('pontos_para_ajuda', models.IntegerField(default=10)),
                ('streak_atual', models.IntegerField(default=0)),
                ('ultimo_dia_atividade', models.DateField(blank=True, null=True)),
                ('nivel', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
