# Generated by Django 5.2.15 on 2026-06-28 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicaoBiblica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('texto_base', models.TextField(help_text='Texto ou referência bíblica')),
                ('referencia', models.CharField(blank=True, help_text='Ex: Gênesis 1:1-31', max_length=100)),
                ('objetivo', models.TextField(blank=True)),
                ('resumo', models.TextField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('xp_recompensa', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Lição Bíblica',
                'verbose_name_plural': 'Lições Bíblicas',
                'ordering': ['trilha', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('faixa_etaria', models.CharField(choices=[('crianca', 'Criança'), ('adolescente', 'Adolescente'), ('adulto', 'Adulto')], default='adulto', max_length=20)),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('icone', models.CharField(default='📖', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MULTIPLA_ESCOLHA', 'Múltipla Escolha'), ('VF', 'Verdadeiro/Falso'), ('ASSOCIACAO', 'Associação'), ('ORDENACAO', 'Ordenação')], default='MULTIPLA_ESCOLHA', max_length=20)),
                ('enunciado', models.TextField()),
                ('dados', models.JSONField(help_text='JSON com alternativas, respostas etc.')),
                ('peso_dificuldade', models.IntegerField(default=1)),
                ('ordem', models.IntegerField(default=0)),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='courses.licaobiblica')),
            ],
            options={
                'ordering': ['licao', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='licaobiblica',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licoes', to='courses.trilha'),
        ),
        migrations.CreateModel(
            name='ProgressoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('xp_ganho_sessao', models.IntegerField(default=0)),
                ('respostas', models.JSONField(blank=True, default=dict)),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.licaobiblica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso do Usuário',
                'verbose_name_plural': 'Progressos dos Usuários',
                'unique_together': {('usuario', 'licao')},
            },
        ),
    ]
