# Generated by Django 5.2.15 on 2026-06-28 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('versiculo', models.CharField(blank=True, max_length=200)),
                ('pergunta', models.TextField(blank=True)),
                ('xp_recompensa', models.IntegerField(default=30)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Desafio Diário',
                'verbose_name_plural': 'Desafios Diários',
            },
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('versiculo', 'Versículo'), ('medalha', 'Medalha'), ('curiosidade', 'Curiosidade'), ('xp_bonus', 'Bônus de XP')], default='medalha', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='🏅', max_length=50)),
                ('xp_recompensa', models.IntegerField(default=100)),
                ('criterio_licoes', models.IntegerField(default=0, help_text='Mínimo de lições concluídas')),
                ('criterio_xp', models.IntegerField(default=0, help_text='XP mínimo')),
                ('criterio_streak', models.IntegerField(default=0, help_text='Streak mínimo')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='SerieOuroDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('faixa_etaria', models.CharField(default='adulto', max_length=20)),
                ('nivel', models.CharField(default='avancado', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('xp_recompensa', models.IntegerField(default=150)),
                ('licao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.licaobiblica')),
                ('trilha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.trilha')),
            ],
            options={
                'verbose_name': 'Série Ouro - Desafio',
                'verbose_name_plural': 'Série Ouro - Desafios',
            },
        ),
        migrations.CreateModel(
            name='SerieOuroExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MULTIPLA_ESCOLHA', 'Múltipla Escolha'), ('VF', 'Verdadeiro/Falso'), ('ASSOCIACAO', 'Associação'), ('ORDENACAO', 'Ordenação')], default='MULTIPLA_ESCOLHA', max_length=20)),
                ('enunciado', models.TextField()),
                ('dados', models.JSONField()),
                ('peso_dificuldade', models.IntegerField(default=2)),
                ('desafio_ouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='gamification.serieourodesafio')),
            ],
        ),
        migrations.CreateModel(
            name='DesafioDiarioConcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=True)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('xp_ganho', models.IntegerField(default=0)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.desafiodiario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'desafio')},
            },
        ),
        migrations.CreateModel(
            name='RecompensaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberto', models.BooleanField(default=False)),
                ('data_desbloqueio', models.DateTimeField(auto_now_add=True)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'recompensa')},
            },
        ),
        migrations.CreateModel(
            name='SerieOuroProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('xp_ganho', models.IntegerField(default=0)),
                ('pontos_para_ajuda_ganhos', models.IntegerField(default=0)),
                ('desafio_ouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.serieourodesafio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'desafio_ouro')},
            },
        ),
    ]
