# Generated by Django 5.2.15 on 2026-06-28 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('LICAO_CONCLUIDA', 'Lição Concluída'), ('DESAFIO_DIARIO', 'Desafio Diário'), ('SERIE_OURO', 'Série Ouro'), ('CHAT_DEVOCIONAL', 'Chat Devocional'), ('DICA_IA', 'Dica da IA'), ('EXPLICACAO_IA', 'Explicação da IA'), ('RECOMPENSA', 'Recompensa'), ('LOGIN', 'Login')], max_length=30)),
                ('referencia', models.CharField(blank=True, help_text='ID ou referência da atividade', max_length=200)),
                ('descricao_resumida', models.TextField(blank=True)),
                ('xp_ganho', models.IntegerField(default=0)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-data_hora'],
            },
        ),
    ]
