# Generated by Django 5.2.15 on 2026-06-28 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoDevocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('fe', 'Fé'), ('esperanca', 'Esperança'), ('gratidao', 'Gratidão'), ('perdao', 'Perdão'), ('oracao', 'Oração'), ('familia', 'Família'), ('proposito', 'Propósito'), ('superacao', 'Superação')], default='fe', max_length=50)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('resumo', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_devocionais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão Devocional',
                'verbose_name_plural': 'Sessões Devocionais',
            },
        ),
        migrations.CreateModel(
            name='MensagemDevocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(choices=[('usuario', 'Usuário'), ('ia', 'IA')], max_length=10)),
                ('texto', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat_devocional.sessaodevocional')),
            ],
            options={
                'verbose_name': 'Mensagem Devocional',
                'verbose_name_plural': 'Mensagens Devocionais',
                'ordering': ['data_hora'],
            },
        ),
    ]
